### ISSUE TITLE
Reveal automatically and fold other folders

### ISSUE THREAD

**Issue by imeed166** [1C0D/Obsidian-Reveal-File-in-explorer#2]
Hi, thank you for the plugin.

I'm not sure if this is within the plugin's scope, but for my use case, I'd like the file to be revealed automatically upon opening. Additionally, it would be great to have an option to fold other folders, leaving only the current file path visible in the file explorer for a cleaner look.

**Comment by 1C0D** [comment]
- "I'd like the file to be revealed automatically upon opening" I'm trying to figure out why. when you are opening a file you click in the explorer so why to reveal the file ? and if you are using another process explain me so I can the utility and if I can it add as an option with a description
- second point I'm using a native obsidian function. But you can do a request feature directly on the obsidian forum to submit this idea of new way to fold unfolding folders using reveal.
This plugin is only making a link between this function and a logical way to trigger it. Even if I keep in mind your suggestion.

**Comment by imeed166** [comment]
1. It's when opening the file with the "quick switcher", the file is not revealed in the file explorer, with the current implementation I have to click to reveal, if it were revealed automatically upon opening it would be faster.
2. Ok, thank you for explaining.

**Comment by 1C0D** [comment]
well correction maybe point 2 is possible.
I tell you later

**Comment by 1C0D** [comment]
@imeed166 Hi I did the second point. this options is now activated by default. much better

**Comment by imeed166** [comment]
awesome, thank you!

**Comment by imeed166** [comment]
As I was using this new feature, I found another benefit to revealing the file automatically :

Say you have 2 folders open, and when you open the file in the first folder using the file explorer, the other folder would be automatically folded.

So it would be beneficial to run upon opening, even when using the file explorer, not only the quick switcher.

**Comment by 1C0D** [comment]
@imeed166 ok first feature done too. you have to turn it on in options first

**Comment by imeed166** [comment]
Ah, it's perfect, thank you. I confirm that it works as intended if enable all options in the settings.

One last question before closing this issue : what's the difference between the first and the last option in the settings 

![image](https://user-images.githubusercontent.com/38974541/230536842-450c4bb1-030d-4e05-a9d0-be8a4a1af3d5.png)

**Comment by 1C0D** [comment]
I must specify better. the 2 last options are working together. this is folding when reveal on file-open happens

**Comment by 1C0D** [comment]
I did a fix to work only if explorer opened. because it was interfering with e.g search.
But I tried with all options enable again in my main vault and the options you made me add are powerfull. ti makes it better for sure

**Comment by imeed166** [comment]
Glad I was able to help ^^
