### ISSUE TITLE
Feature Request : ignoring some folder

### ISSUE THREAD

**Issue by gynl** [1C0D/Obsidian-Reveal-File-in-explorer#7]
Hi,

First of all, thank you for your work on this pluggin ! This is great and perfectly match with my needs.

The only potential improvement I see would be to allow the option of excluding certain folders.
Specifically, the "diary" folder, which contains numerous files and is easier to navigate through the calendar.

**Comment by 1C0D** [comment]
I did an update to add an option to not reveal files when opening them from the explorer. So they will just revealed if clicking on the header title or using the quick switcher. 
Is it enough in your situation, or you prefer to always have the reveal and then exclude some folders ? 
Just to know if it is still relevant to add this option.

**Comment by 1C0D** [comment]
I added the option you asked. For the moment I chose a simple solution for the interface, but maybe later I chose a more advanced solution, using the quick switcher... But this is working

**Comment by gynl** [comment]
Simple but effective. Thank you for considering my request. It's perfect like that.
Thank you again for your work!

**Comment by gynl** [comment]
I do not remember if I did it yet but… Thanks a lot for that !


*Geoffrey **Nimal *
B-7190 Marche-lez-Écaussinnes, rue du Bois de Feluy 1
064/700.136 – 0478 296 112

------------------------------
<http://bepo.fr>
