### ISSUE TITLE
Losing focus in Canvas when creating a new card with double click

### ISSUE THREAD

**Issue by jeffgyf** [1C0D/Obsidian-Reveal-File-in-explorer#8]
When plugin is enabled, focus will be lost after double clicking in canvas for creating a new card.

**Comment by 1C0D** [comment]
Ok fixed deactivated on canvas files. The lazy way, but I don't see why this is changing the active file. Maybe I will ask on the forum to see

**Comment by 1C0D** [comment]
ok fixed. thnks for reporting this
